// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"erp/internal/interfaces/cleanhandler"
	"erp/internal/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// BuildAggregatorPayoutHandler создаёт хендлер через wire.
// Реальная реализация появится в wire_gen.go после генерации.
func BuildAggregatorPayoutHandler(db *gorm.DB) (*cleanhandler.AggregatorPayoutHandler, func(), error) {
	aggregatorPayoutRepository := wire.ProvideAggPayoutRepo(db)
	aggregatorPayoutUseCase := wire.ProvideAggPayoutUC(aggregatorPayoutRepository)
	aggregatorPayoutHandler := cleanhandler.NewAggregatorPayoutHandler(aggregatorPayoutUseCase)
	return aggregatorPayoutHandler, func() {
	}, nil
}
