name: Deploy Backend

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/deploy/www/erp-dez/back
            git pull origin master
            docker compose build erp-app
            docker compose run --rm migrate up
            docker compose up -d erp-app mysql redis